### ISSUE TITLE
video

### ISSUE THREAD

**Issue by jocheml0cked** [jocheml0cked/london-webite-#1]
video is tog niet goed gelinked, het moet gewoon een <video worden, niet zon YouTube layout iets..

**Comment by coenwesterink** [comment]
Gefixt, de link moest ipv watch, embed...

EDIT:

Heb er een iframe van gemaakt, werkt nu wél naar behoren

**Comment by jocheml0cked** [comment]
hey coen thx maar hij geeft nog steeds ongeldige  bron aan, ligt dat aan
mij?

2016-05-31 19:31 GMT+02:00 coenwesterink notifications@github.com:

**Comment by jocheml0cked** [comment]
laat maar mijn fout

2016-05-31 19:31 GMT+02:00 coenwesterink notifications@github.com:
