### ISSUE TITLE
linken

### ISSUE THREAD

**Issue by jocheml0cked** [jocheml0cked/london-webite-#3]
het linken gaat nog fout, wachten met fixen tot alle bestanden klaar zijn, doen we alles ter gelijk
bijkomende bestanden:

map.html
Script.html

**Comment by coenwesterink** [comment]
Wat doen map en script?

**Comment by jocheml0cked** [comment]
Map is een Api google maps
Script daar komt de volledige code in net ALS bij Reis langs de Donau

Op woensdag 1 juni 2016 heeft coenwesterink notifications@github.com het
volgende geschreven:
